### PR TITLE
Fix Sign Transaction Signature

### LINKED ISSUE #124: Error verifying the signature using DAppConnector.signTransaction()
**Describe the bug** A clear and concise description of what the bug is.

In our testing of the signTransaction functionality from ioBuilders for integration into the Hedera Stablecoin project, we have encountered an issue with signature verification. The current implementation fails to verify signatures within our testing environment. Interestingly, we have successfully verified signatures using Blade, HasPack, and Metamask wallets.

In an attempt to address this, we modified our code to verify transactions created with hedera-wallet-connect against a customized verification function. However, when these transactions were submitted to the Hedera Network for verification, they were rejected. This discrepancy leads us to suspect that the signTransaction method may be producing incorrect signatures, possibly due to inaccuracies in the signed bytes generated.

**To Reproduce** Steps to reproduce the behavior:

1. Clone the Hedera Stablecoin repository
2. Setup Stablecoin with a backend for multi-signature instance
3. Use a multi-signature account to create a cash in transaction (for example)
4. Use a Wallet Connect connection wallet to sign the previously created transaction
5. Verification exception should be thrown from the backend

**Expected behavior** A clear and concise description of what you expected to happen.

The same verification process should verify signatures from hedera-wallet-connect.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Brave (chrome)

### PR DESCRIPTION
**Pull request by MiguelLZPF**
## Description

Changed the transaction bytes to be signed. More details available in the issue.

**Fixes #124**

### CODE REVIEW

**Comment by franfernandez20** [comment]
I recommend resolving this issue by reverting the implementation to `Transaction.toBytes()` and `Transaction.fromBytes()`. This approach not only resolves the problem but also eliminates the need to use private SDK methods. Additionally, it restores the capability to set multiple nodeIds. 
Consequently, we should update the definition in the WalletConnect documentation for [hedera_signTransaction](https://specs.walletconnect.com/2.0/blockchain-rpc/hedera-rpc#hedera_signtransaction) to reflect these changes.

**Comment by bugbytesinc** [comment]
The multiple node id concept pulls against the intent of the wallet connect infrastructure, it is the source of other bugs and potential future exploits.  Also, supporting multiple transactions in this could break conformity with HIP-820.  The private methods are used because part of the constraints when creating the library was that "the JS sdk could not be changed in any way".

**Comment by bugbytesinc** [comment]
The real fix is to fix the JS SDK first, so it can support the proper wallet connect functionality.

**Comment by gregscullard** [comment]
> I recommend resolving this issue by reverting the implementation to `Transaction.toBytes()` and `Transaction.fromBytes()`.

Given this PR suggests a change to how a `transactionBody` is "extracted" from a Transaction, suggest we keep the conversation here relevant to this change and discuss support for to/fromBytes separately.

The prior implementation extracted a `transactionBody` from the Transaction and created a new body using a nodeAccountId that was selected at random by the library, thereby changing the transaction body prior to requesting a signature.

For example: If a developer created a transaction using the SDK, specified exactly one node he/she wanted to use, the library arbitrarily selected a different node (it could be the same thanks to randomness, but no guarantee)
The proposed change remains faithful to the developer's node selection.

File: src/lib/shared/utils.ts [hunk 1]
```diff
@@ -98,17 +98,14 @@ export function base64StringToTransaction<T extends Transaction>(transactionByte
  * @param transaction - a base64 encoded string of proto.TransactionBody.encode().finish()
  * @returns `string`
  * */
-export function transactionToTransactionBody<T extends Transaction>(
-  transaction: T,
-  nodeAccountId: AccountId,
-) {
+export function transactionToTransactionBody<T extends Transaction>(transaction: T) {
```
Comment (gregscullard) [inline src/lib/shared/utils.ts:101]: I'm uncomfortable changing the signature of a public method, this could result in a breaking change to existing implementations.

Comment (gregscullard) [reply src/lib/shared/utils.ts:101]: Maybe this implementation should remain and `Signer.ts` changed from 

```async signTransaction<T extends Transaction>(transaction: T): Promise<T> {
    const transactionBody: proto.TransactionBody = transactionToTransactionBody(
      transaction,
      this._getRandomNodes(1)[0],
    )
```

to re-using the `nodeAccountId` from `transaction` (if that's possible) ?

This would no longer be a breaking change.

Comment (MiguelLZPF) [reply src/lib/shared/utils.ts:101]: Thanks for the feedback! 🙂

From our testing and research, the method used in this PR is the only way to get the signed transaction validated by the Hedera network. The previous approach signed the transaction in a way that the Hedera Network couldn't verify.

That said, we can leave the nodeAccountId parameter for compatibility, although it's currently unused and likely not functional in its previous form. @gregscullard, should I include the nodeAccountId as you suggested?

If there is a better method to obtain the signed transaction bytes than the one used in this PR, please let me know. Based on our testing a few weeks ago, this was the only approach that worked.

File: test/dapp/DAppConnector.test.ts [hunk 2]
```diff
@@ -295,7 +295,7 @@ describe('DAppConnector', () => {
         signerAccountId: testUserAccountId.toString(),
         transactionBody: transactionBodyToBase64String(
           // must specify a node account id for the transaction body
-          transactionToTransactionBody(transaction, AccountId.fromString('0.0.3')),
+          transactionToTransactionBody(transaction),
```
Comment (gregscullard) [inline test/dapp/DAppConnector.test.ts:298]: Note, remove comment on line 297, it's no longer relevant

**Review by gregscullard — CHANGES_REQUESTED** [review]

File: src/lib/shared/utils.ts (hunk 1 above)
Comment (gregscullard) [reply src/lib/shared/utils.ts:101]: I'll leave it to the community of builders/users to determine whether a breaking change in the signature of the transaction is acceptable or not. The change is minor and would likely be implemented as a result of changes to the application, so tested and working before deployed. Breaking but not critically so I guess.

File: package.json [hunk 3]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "@hashgraph/hedera-wallet-connect",
-  "version": "1.3.1",
+  "version": "22.0.0",
```
Comment (tmctl) [inline package.json:3]:
```suggestion
  "version": "1.3.3-0",
```

File: src/lib/shared/utils.ts [hunk 4]
```diff
@@ -100,15 +100,15 @@ export function base64StringToTransaction<T extends Transaction>(transactionByte
  * */
 export function transactionToTransactionBody<T extends Transaction>(
   transaction: T,
-  nodeAccountId: AccountId,
+  nodeAccountId: AccountId, // To mantain compatibility
 ) {
   // This is a private function, though provides the capabilities to construct a proto.TransactionBody
   //@ts-ignore
-  return transaction._makeTransactionBody(nodeAccountId)
+  return transaction._signedTransactions.current.bodyBytes
```
Comment (tmctl) [inline src/lib/shared/utils.ts:107]: This utility function is used to get the transaction body before the transaction is signed, based on the name of _signedTransactions, I'd imagine this internal function only has the transactions in this array if the transaction has already been signed?

If so, we may need to try another method

@MiguelLZPF

**Review by tmctl — COMMENTED** [review]
added another comment about accessing _signedTransactions, would the transaction body be in that array before a transaction is signed?

File: src/lib/shared/utils.ts (hunk 4 above)
Comment (MiguelLZPF) [reply src/lib/shared/utils.ts:107]: Hi @tmctl! if I understood you correctly, there is a problem getting the signed transaction body here because this utility function was intended to get the transaction body not the signed transaction body.
So, the original issue is that HederaWalletConnect is getting the transaction body also when it should be looking for the signed transaction body.
So the solution is to have two separate utility functions then, right?

File: package.json (hunk 3 above)
Comment (MiguelLZPF) [reply package.json]: Updated with main branch, thanks

File: src/lib/shared/utils.ts (hunk 4 above)
Comment (MiguelLZPF) [reply src/lib/shared/utils.ts:120]: Added in the latest commit, take a look at it and tell me what you guys think 🤔

Comment (MiguelLZPF) [reply src/lib/shared/utils.ts:107]: I've reverted the change; the issue was with the naming. `transaction._signedTransactions.current.bodyBytes` actually contains the UNSIGNED transaction body bytes, which makes sense since this occurs before the transaction is signed. It was confusing initially because of the misleading name, as you pointed out in your previous message.

Comment (MiguelLZPF) [reply src/lib/shared/utils.ts:107]: This is the signed transaction bytes: `signedTransaction._transactions.current.signedTransactionBytes` 🫣. In my opinion is mega-difficult to understand this structure...

**Comment by MiguelLZPF** [comment]
Just to add more clarity about this topic, this are our testing results for only sign Hedera SDK Transaction Objects:
```typescript
  const fullTxBytes = transaction.toBytes();
  const transactionBytes = transaction._signedTransactions.get(0)!.bodyBytes!; //* <--
  const signedTransactionBytes = signedTransaction._transactions.get(0)!.signedTransactionBytes!;
  const signatures = signedTransaction.getSignatures().get(newAccountId)!;
  const transactionHash = await signedTransaction.getTransactionHash();
console.log(`
    Full Transaction: ${uint8ArrayToHex(fullTxBytes)}
    Transaction: ${uint8ArrayToHex(transactionBytes)}
    Signed Transaction: ${uint8ArrayToHex(signedTransactionBytes)}
    Tx Hash: ${uint8ArrayToHex(transactionHash)}
    Signature: ${uint8ArrayToHex(signatures.get(privateKey.publicKey)!)
')
```

**Review by jeromy-cannon — APPROVED** [review]

**Review by gregscullard — APPROVED** [review]
LGTM
